[project]
name = "steiza-python-oidc-test"
version = "0.0.1"
description = "testing OIDC publish"
readme = "README.md"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
